version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez
        columns:
          - name: date_date
          - name: orders_id
          - name: products_id
          - name: revenue
          - name: quantity
      - name: product
        identifier: raw_gz_product
        description: product of greenweez
        columns:
          - name: products_id
          - name: purchase_price
              
      - name: ship
        identifier: raw_gz_ship
        description: ship of greenweez
        columns:
          - name: orders_id
          - name: shipping_fee
          - name: logcost
          - name: ship_cost
      - name: adwords
        identifier: raw_gz_adwords
        columns: 
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: campaign_name  
          - name: ads_cost
          - name: impression
          - name: click

      - name: bing
        identifier: raw_gz_bing
        columns: 
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: campaign_name  
          - name: ads_cost
          - name: impression
          - name: click
      - name: criteo
        identifier: raw_gz_criteo
        columns: 
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: campaign_name  
          - name: ads_cost
          - name: impression
          - name: click  
      - name: facebook
        identifier: raw_gz_facebook
        columns: 
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: campaign_name  
          - name: ads_cost
          - name: impression
          - name: click  

models:
  - name: stg_raw__sales
    description: clean
    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"
  - name: stg_raw__product
    description: clean
    columns:
      - name: products_id
        description: primary
        tests:
          - unique
          - not_null
  - name: stg_raw__ship
    description: clean
    columns:
      - name: orders_id
        description: primary
        tests:
          - unique
          - not_null
  - name: stg_raw_adwords
    columns:
      - name: date_date
        tests:
          - unique
          - not_null
  - name: stg_raw_bing
    columns:
      - name: date_date
        tests:
          - unique
          - not_null
  - name: stg_raw_criteo
    columns:
      - name: date_date
        tests:
          - unique
          - not_null
  - name: stg_raw_facebook
    columns:
      - name: date_date
        tests:
          - unique
          - not_null
          